### ISSUE TITLE
Question: stay in sync with template repo

### ISSUE THREAD

**Issue by rafaelderolez** [jetskis/midway#8]
Hey Kevin,

Figured this was the best place to ask as others might run into this as well.
What's the best way of using this template, but keeping up with its changes along the line?

I've been cherry-picking the last few commits but I'm thinking there is a better way.

✌️

**Comment by iamkevingreen** [comment]
@rafaelderolez I think the way I would have to compartmentalize things would potentially seriously complicate this. I'm not really sure how projects like even gatsby itself handle this? I generally stay away from updating things in my projects unless I am at a point where 2-3 months time has passed. 

I will say for the most part aspects of this that do change should be completely replaceable or cherry-pickable. The Shopify-Sync function follows all the same logic (though totally rewritten) but now simply checks Sanity first to see if updates need to be made. If you had extended your Sync or modified the product structure merging these changes would break so I'd not want this to be a package that overrides files or has to do diff/checks against them. 

I am using this: https://github.com/ctrl-alt-del-world/midway/releases

Which I can get more granular and specific about files/functions changing so that it makes it easier to track what is changing and updating. I also generally only have windows (in between projects) where I am making explicit updates, so sorry that it's a weird cycle of updates. 

Happy to discuss other-ways to make this easier to stay in sync, especially with things like the Shopify-Sync update that I think does benefit anyone using this experience. 


### Another Note--

This is also a template repo, so it's sort of purpose is to be a resource, while you can use the whole thing to bootstrap all these pieces, it's also sort of meant to be picked apart for the needs of your projects. All the Lambda functions for example could easily be dropped into a Next.js project if so desired. :) I am working with the Sanity peeps to make aspects of this Sanity-Create so it may change some of the ongoing dev work here, more on that soon!

**Comment by iamkevingreen** [comment]
@rafaelderolez I will continue to use releases, but also have enabled discussions so it's hopefully easier to open, discuss things that are changing there. https://github.com/ctrl-alt-del-world/midway/discussions
